object Versions{
    const val androidCompileSdk = 29
    const val androidMinSdk = 24
    const val androidTargetSdk = 29
    const val appCompat = "1.1.0"
    const val core = "1.1.0"
    const val constraintLayout = "1.1.3"
    const val design = "29.0.0"
    const val recylerView = "29.0.0"
    const val dagger = "2.25.4"
    const val retrofit2 = "2.6.1"
    const val converterGson = "2.6.1"
    const val okHttp = "4.3.0"
    const val jUnit = "4.12"
    const val runner = "1.2.0"
    const val espresso = "3.2.0"
    const val mockito = "3.0.0"
    const val junitExt = "1.1.1"
    const val mockWebServer = "4.3.0"
    const val rxJava = "2.2.10"
    const val rxAndroid = "2.1.1"
    const val adapterRxJava = "2.6.1"
    const val glide = "4.9.0"
    const val legacySupportV4 = "1.0.0"
    const val glideCompiler = "4.9.0"
    const val roomRuntime = "2.2.3"
    const val roomCompiler = "2.2.3"
    const val roomRxJava2 = "2.2.3"
    const val gson = "2.8.5"
    const val roomKtx = "2.2.3"
    const val coroutineCore = "1.3.2"
    const val coroutineAndroid = "1.3.2"
}

object AppDependencies{
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val core = "androidx.core:core-ktx:${Versions.core}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val design = "com.android.support:design:${Versions.design}"
    const val recyclerView = "com.android.support:recyclerview-v7:${Versions.recylerView}"
    const val daggerAndroid = "com.google.dagger:dagger-android:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val daggerAndroidSupport = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val daggerProcessor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val retrofit2 = "com.squareup.retrofit2:retrofit:${Versions.retrofit2}"
    const val converterGson = "com.squareup.retrofit2:converter-gson:${Versions.converterGson}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    const val rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    const val adapterRxJava = "com.squareup.retrofit2:adapter-rxjava2:${Versions.adapterRxJava}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val legacySupportV4 = "androidx.legacy:legacy-support-v4:${Versions.legacySupportV4}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glideCompiler}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.roomRuntime}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.roomCompiler}"
    const val roomRxJava2 = "androidx.room:room-rxjava2:${Versions.roomRxJava2}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.roomKtx}"
    const val coroutineCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutineCore}"
    const val coroutineAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutineAndroid}"
}

object TestDependencies{
    const val jUnit = "junit:junit:${Versions.jUnit}"
    const val runner = "androidx.test:runner:${Versions.runner}"
    const val espressoCore= "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val mockito = "org.mockito:mockito-core:${Versions.mockito}:"
    const val rule = "androidx.test:rules:${Versions.runner}"
    const val truth = "androidx.test.ext:truth:${Versions.runner}"
    const val junitExt = "androidx.test.ext:junit:${Versions.junitExt}"
    const val mockWebServer = "com.squareup.okhttp3:mockwebserver:${Versions.mockWebServer}"
}